select * from Book
select * from book
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'计算机网络','Peter',60.51,N'机械工业出版社',2002/1/1,N'教育',N'教材,本科教材,计算机',N'二十年经久不衰，销量超过400万册，不断出新的经典教科书','/Images/book1-1','/Images/book1-2','/Images/1-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'计算机原理','Peter',50.5,N'南海出版公司',2002/2/1,N'教育',N'教材,本科教材,计算机',N'本书是学习计算机原理与体系结构非常实用的案例教材！','/Images/book2-1','/Images/book2-2','/Images/book2-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'机器学习','Pearson',78.1,N'花城出版社',2002-03-01,N'科技',N'人工智能',N'击败AlphaGo的武林秘籍，赢得人机大战的必由之路：人工智能大牛周志华教授巨著，全面揭开机器学习的奥秘','/Images/book3-1','/Images/book3-2','/Images/book3-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'数据库概论',N'王珊',53.3,N'花城出版社','2009-04-01',N'教育',N'教材,计算机,本科教材',N'国内计算机组成原理课程经典教材，多所重点高校计算机研究生考试指定参考书。','/Images/book4-1','/Images/book4-2','/Images/book4-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'Java程序设计',N'马皓',51.3,N'北京文艺出版社','2002-05-01',N'教育',N'教材,计算机,本科教材',N'Java语言程序设计（基础篇）（原书第11版）','/Images/book5-1','/Images/book5-2','/Images/book5-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'C++程序设计',N'郑莉',49.1,N'北京文艺出版社','2006-06-01',N'教育',N'教材,计算机,本科教材',N'十二五”普通高等教育本科*规划教材、北京市高等教育精品教材立项项目、全国高校出版社优秀畅销书特等奖。发行逾1400万册，堪称出版界的奇迹。','/Images/book6-1','/Images/book6-2','/Images/book6-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'VB.NET程序设计',N'龚沛曾',50.8,N'北京十月文艺出版社',N'2002-07-01',N'教育',N'教材,计算机,本科教材',N'由浅入深地介绍了VB.NET开发环境和各种控件的使用方法，通过实际应用阐述VB.NET的编程方法。','/Images/book7-1','/Images/book7-2','/Images/book7-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'追风筝的人',N'卡勒德·胡',40.2,N'上海人民出版社','2002-8-1',N'小说',N'外国小说,世界名著',N'为你，千千万万遍！快乐大本营高圆圆感动推荐，朗读者张一山深情诵读，窦靖童创作灵感的来源，奥巴马送给女儿的新年礼物。','/Images/book8-1','/Images/book8-2','/Images/book8-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'百年孤独',N'加西亚·马',55.4,N'南海出版公司','2002-9-1',N'小说',N'外国小说,世界名著',N'50周年纪念版！全新典藏内封，限量赠50周年精美魔幻明信片1套。马尔克斯代表作，全球惟一正式授权中文版，未作任何删节！6年发行量超600万册！','/Images/book9-1','/Images/book9-2','/Images/book9-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'霍乱时期的爱情',N'加西亚·马',34.5,N'南海出版公司','2002-10-1',N'小说',N'外国小说,世界名著',N'讲述了一段跨越半个多世纪的爱情史诗，穷尽了所有爱情的可能性：忠贞的、隐秘的、粗暴的、羞怯的、柏拉图式的、放荡的、转瞬即逝的、生死相依的……马尔克斯曾说：“这一部是我*好的作品，是我发自内心的创作。”是20世纪*重要的经典文学巨著之一，被誉为“人类有史以来*伟大的爱情小说”。','/Images/book10-1','/Images/book10-2','/Images/book10-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'活着',N'余华',58.8,N'南海出版公司','2002-11-1',N'小说',N'社会,中国近现代小说',N'余华是我国当代著名作家，也是享誉世界的小说家，曾荣获众多国内外奖项。《活着》是其代表作，在全球广泛传播，销量逾千万册，获得了普遍好评，已成为中国乃至世界当代文学的经典。','/Images/book11-1','/Images/book11-2','/Images/book11-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'围城',N'钱锺书',59.9,N'人民文学出版社','2002-12-1',N'小说',N'情感,中国当代小说',N'凡是真正出色的文学作品，都具有一种抗理论分析力，任何自认为深透、精彩的理论都会在它们面前显得干瘪而又捉襟见肘。','/Images/book12-1','/Images/book12-2','/Images/book12-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'平凡的世界（全三部）',N'路遥',	60,N'人民文学出版社','2003-1-1',N'小说',N'社会,中国近现代小说',N'新晋男神朱一龙推荐阅读。茅盾文学奖皇冠上的明珠，激励亿万读者的不朽经典。深受老师和学生喜爱的新课标必读书','/Images/book13-1','/Images/book13-2','/Images/book13-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'白鹿原',N'陈忠实',61,N'人民文学出版社'	,'2003-2-1',N'小说'	,N'社会,中国近现代小说',N'一部渭河平原的雄奇史诗，一幅中国农村的斑斓画卷。主人公白嘉轩六娶六丧，奇异的命运序曲预示着不祥。','/Images/book14-1','/Images/book14-2','/Images/book14-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'肖申克的救赎',N'斯蒂芬·金',62,N'人民文学出版社','2003-3-1',N'小说',N'社会,外国小说',N'同名电影豆瓣评论数超过一百万！斯蒂芬·金广为人知的作品，一部不朽的励志经典，每个青年人都应该拥有的希望之书。同名电影入选美国电影学会20世纪百大电影清单','/Images/book15-1','/Images/book15-2','/Images/book15-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'黄金时代',N'王小波',63,N'花城出版社','2003-4-1',N'小说',N'社会,中国近现代小说',N'早期手稿首次曝光，李银河倾情推荐，朱大可、李静作序。制作精良，性价比远超其他版本！ （我过二十一岁生日时，觉得自己会永远生猛下去，那是我一生的黄金时代。）','/Images/book16-1','/Images/book16-2','/Images/book16-3',2	,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'飘',N'玛格丽特',64,N'译林出版社','2003-5-1',N'小说',N'社会,外国小说,世界名著',N'真正的无删节全译本，较市面通行版本多30000字。普利策奖获奖作品，21世纪现代女性必读的人生四书之一。《我们仨》作者杨绛先生说：“看《飘》，就犹如走进原始森林，越深越美。”','/Images/book17-1','/Images/book17-2','/Images/book17-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'灿烂千阳',N'卡勒德·胡',65,N'上海人民出版社','2003-6-1',N'小说',N'社会,外国小说',N'《追风筝的人》作者作者献给阿富汗女性的动人故事。关于不可宽恕的时代，不可能的友谊以及不可毁灭的爱。','/Images/book18-1','/Images/book18-2','/Images/book18-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'倾城之恋',N'张爱玲',66,N'花城出版社','2003-7-1',N'小说',N'情感,中国当代小说',N'到处都是传奇，可不见得有这么圆满的收场。胡琴咿咿哑哑拉着，在万盏灯的夜晚，拉过来又拉过去，说不尽的苍凉的故事不问也罢！”','/Images/book19-1','/Images/book19-2','/Images/book19-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'芳华',N'严歌苓',67,N'人民文学出版社','2003-8-1',N'小说',N'社会,中国近现代小说',N'冯小刚导演、黄轩主演同名电影正在热映！青春不是年华，是你我的芳华。','/Images/book20-1','/Images/book20-2','/Images/book20-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'情人',N'玛格丽特',68,N'上海译文出版社','2003-9-1',N'小说',N'情感,外国小说',N'《情人》是玛格丽特·杜拉斯*负盛名的代表作，曾荣获获一九八四年法国龚古尔文学奖，同名电影的拍摄也加深了中国读者对它的了解。全书以法国殖民者在越南的生活为背景，描写贫穷的法国女孩与富有的中国少爷之间深沉而无望的爱情。','/Images/book21-1','/Images/book21-2','/Images/book21-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'挪威的森林',N'村上春树',69,N'上海译文出版社','2003-10-1',N'小说',N'社会,外国小说',N'村上春树的残酷青春物语，现象级的超级畅销书，纪念《挪威的森林》问世30周年','/Images/book22-1','/Images/book22-2','/Images/book22-3',1,'5')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'边城',N'沈从文',70,N'北京文艺出版社','2003-11-1',N'小说',N'社会,中国近现代小说',N'被誉为 “中国现代文学牧歌传说中的佳作”，教育部推荐中小学必读名著！','/Images/book23-1','/Images/book23-2','/Images/book23-3',2,'100,40')
insert into Book(BookName,BookWriter,BookPrice,BookPublisher,PublishTime,BookType,Tag,BookAbstract,Picture1,Picture2,Picture3,Coupon,CouponDetail)
values(N'人民的名义',N'周梅森',71,N'北京十月文艺出版社','2003-12-1',N'小说',N'官场,中国近现代小说',N'根据本书改编而成的同名电视剧正在热播，由陆毅、张丰毅等40余名实力戏骨联袂出演！著名作家周梅森潜心八年、六易其稿，一部反腐高压下中国政治和官场生态的长幅画卷。','/Images/book24-1','/Images/book24-2','/Images/book24-3',2,'100,40')
